format_version: 3
environments:
  gocd:
    pipelines:
      - installer-tests
pipelines:
  installer-tests:
    group: go-cd
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      GO_VERSION: 25.4.0
    tracking_tool:
      link: https://github.com/gocd/gocd/issues/${ID}
      regex: '##(\d+)'
    materials:
      git:
        git: https://git.gocd.io/git/gocd/installer-testing
        blacklist:
        - '*.md,pipeline-as-code/*'
        shallow_clone: true
        auto_update: true
        branch: master
      installers:
        pipeline: installers
        stage: dist
        name: installers
      metadata-uploaded-and-cdn-refreshed:
        pipeline: code-sign
        stage: cloudfront-invalidation
        name: code-sign
    stages:
    - install-tests:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          fresh-install:
            timeout: 0
            run_instances: '7'
            elastic_profile_id: installers-testing-arm64
            tasks:
            - exec:
                command: bash
                # See https://github.com/moby/moby/issues/30880#issuecomment-798807332 for why normal docker login to docker.gocd.io as registry mirror doesn't work
                # Docker uses the wrong credentials when trying to use a registry mirror, so we set the docker.gocd.io creds for Docker Hub
                arguments: [ -c, 'mkdir -p ~/.docker && echo "{ \"auths\": { \"https://index.docker.io/v1/\": { \"auth\": \"$(echo -n "${DOCKERHUB_MIRROR_USERNAME}:${DOCKERHUB_MIRROR_PASSWORD}" | base64)\" } } }" > ~/.docker/config.json' ]
            - exec:
                command: rake
                arguments: [ test_installers ]
          upgrade:
            timeout: 0
            run_instances: '7'
            environment_variables:
              UPGRADE_VERSIONS_LIST: 20.5.0-11820
            elastic_profile_id: installers-testing-x64
            tasks:
            - exec:
                command: bash
                # See https://github.com/moby/moby/issues/30880#issuecomment-798807332 for why normal docker login to docker.gocd.io as registry mirror doesn't work
                # Docker uses the wrong credentials when trying to use a registry mirror, so we set the docker.gocd.io creds for Docker Hub
                arguments: [ -c, 'mkdir -p ~/.docker && echo "{ \"auths\": { \"https://index.docker.io/v1/\": { \"auth\": \"$(echo -n "${DOCKERHUB_MIRROR_USERNAME}:${DOCKERHUB_MIRROR_PASSWORD}" | base64)\" } } }" > ~/.docker/config.json' ]
            - exec:
                command: rake
                arguments: [ upgrade_tests ]
